### ISSUE TITLE
Fix Padding Issue in Sudoku Grid Rows

### ISSUE THREAD

**Issue by katarinakovacova** [katarinakovacova/gridoku#33]
## Description
There is an issue with the padding in the Sudoku grid where, if a row is missing numbers, the entire row shrinks. This leads to inconsistent row heights and affects the overall layout.

## Tasks
- [ ] Investigate the cause of the shrinking rows when numbers are missing.
- [ ] Ensure that each row maintains consistent height regardless of the number of digits.
- [ ] Adjust the CSS/SCSS to apply proper padding and spacing to prevent shrinking.
- [ ] Test the solution on all possible grid states (empty, partially filled, fully filled).

<img width="885" alt="Snímka obrazovky 2024-10-23 o 10 38 01" src="https://github.com/user-attachments/assets/43fc3851-8605-4d26-a71d-dec268d53b3b">

## Acceptance Criteria
- Each row in the Sudoku grid maintains a consistent height, even when numbers are missing.
- The grid layout remains stable across different screen sizes.
- The CSS/SCSS code is clean and does not introduce any other layout issues.
