### ISSUE TITLE
 Fix Blurring of Level Selection Bar When Timer Stops

### ISSUE THREAD

**Issue by katarinakovacova** [katarinakovacova/gridoku#35]
## Description
When the timer, which blurs the Sudoku grid, is stopped, the level selection bar also becomes blurred. This issue affects the visibility and usability of the level selection bar, which should remain clear and unaffected by the grid blur effect.

## Tasks
- [ ] Investigate why the level selection bar is being blurred when the timer stops.
- [ ] Ensure that the blur effect only applies to the Sudoku grid and not to the level selection bar.
- [ ] Adjust the CSS/JavaScript to isolate the blur effect to the grid.
- [ ] Test the solution by stopping and restarting the timer and interacting with the level selection bar.

<img width="901" alt="Snímka obrazovky 2024-10-23 o 10 45 06" src="https://github.com/user-attachments/assets/c87f82b1-a422-44ba-b62d-d394ee69f8d7">

## Acceptance Criteria
- The level selection bar remains clear and unaffected when the timer is stopped.
- The blur effect only applies to the Sudoku grid and not any other UI elements.
- The user can interact with the level selection bar without visual issues when the timer is stopped.
