### ISSUE TITLE
 Add Image to Project and Update README

### ISSUE THREAD

**Issue by katarinakovacova** [katarinakovacova/gridoku#41]
## Description
We need to add an image to the Gridoku project for use in the README file.

## Tasks
- [x] Create an `images` directory inside the `sudoku/static/sudoku` directory.
- [x] Add the image file (e.g., `your_image.png`) to the `images` directory.
- [x] Update the Django template to include the image using the `{% static %}` tag.
- [x] Add the image reference to the `README.md` file using Markdown syntax.

## Acceptance Criteria
- The image is successfully added to the project structure.
- The image is displayed correctly in the relevant Django template.
- The image is included in the `README.md` file and displays correctly on GitHub.
